services:
  db:
    image: postgres:15-alpine
    container_name: stocksim-db
    environment:
      POSTGRES_DB: stocksim
      POSTGRES_USER: stocksim
      POSTGRES_PASSWORD: stocksim
    # Do NOT publish the DB port publicly in production
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  web:
    build: .
    container_name: stocksim-web
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Provide via server .env (not committed)
      SECRET_KEY: ${SECRET_KEY:?set SECRET_KEY in .env}
      DATABASE_URL: postgresql://stocksim:stocksim@db:5432/stocksim
      ALPACA_API_KEY: ${ALPACA_API_KEY:-}
      ALPACA_SECRET_KEY: ${ALPACA_SECRET_KEY:-}
    # Expose only to the internal network; Caddy will reverse proxy
    expose:
      - "8000"
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: stocksim-caddy
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN: ${DOMAIN:?set DOMAIN in .env}
      EMAIL: ${EMAIL:-}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web
    restart: unless-stopped

volumes:
  pgdata:
  caddy_data:
  caddy_config:
